### ISSUE TITLE
What's the difference between this project and mattgathu/slugify?

### ISSUE THREAD

**Issue by tad-lispy** [spa5k/slugify-rs#5]
Hello! Thank you for publishing this. I was looking for a crate to help me generate slugs and among many others found yours and https://github.com/mattgathu/slugify/. Now I'm a bit confused, because they look very similar. Yours is new and I see in the readme that you credit @mattgathu, but the relation between them is not clear. What are the benefits of using this crate over the other?

**Comment by spa5k** [comment]
There were some pending prs in the original crate which weren't merged for quite long, so I created this one. Don't remember much about it tho.

**Comment by spa5k** [comment]
Iirc i added few new macros
